//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DQ.OD.DBProvider.ADService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ADService.IADService")]
    public interface IADService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADService/CheckADUser", ReplyAction="http://tempuri.org/IADService/CheckADUserResponse")]
        bool CheckADUser(string sUserName, string sPassword, ref string strDBConString);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IADServiceChannel : DQ.OD.DBProvider.ADService.IADService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ADServiceClient : System.ServiceModel.ClientBase<DQ.OD.DBProvider.ADService.IADService>, DQ.OD.DBProvider.ADService.IADService {
        
        public ADServiceClient() {
        }
        
        public ADServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ADServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ADServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ADServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CheckADUser(string sUserName, string sPassword, ref string strDBConString) {
            return base.Channel.CheckADUser(sUserName, sPassword, ref strDBConString);
        }
    }
}
